//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBaseSoftwareProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImgId { get; set; }
        public byte[] StoredImg { get; set; }
        public int User_ID { get; set; }
    }
}
